package chtcp

const (
	DBMS_MIN_REVISION_WITH_SERVER_DISPLAY_NAME            = 54372
	DBMS_MIN_REVISION_WITH_VERSION_PATCH                  = 54401
	DBMS_MIN_REVISION_WITH_CLIENT_WRITE_INFO              = 54420
	DBMS_MIN_REVISION_WITH_SETTINGS_SERIALIZED_AS_STRINGS = 54429
	DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET             = 54441
	DBMS_MIN_REVISION_WITH_OPENTELEMETRY                  = 54442
)
