package chtcp

const (
	DBMS_MIN_REVISION_WITH_SERVER_DISPLAY_NAME               = 54372
	DBMS_MIN_REVISION_WITH_VERSION_PATCH                     = 54401
	DBMS_MIN_REVISION_WITH_SETTINGS_SERIALIZED_AS_STRINGS    = 54429
	DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET                = 54441
	DBMS_MIN_PROTOCOL_VERSION_WITH_ADDENDUM                  = 54458
	DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS                = 54459
	DBMS_MIN_REVISION_WITH_OPENTELEMETRY                     = 54442
	DBMS_MIN_PROTOCOL_VERSION_WITH_PASSWORD_COMPLEXITY_RULES = 54461
	DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET_V2             = 54462
	DBMS_MIN_REVISION_WITH_CLIENT_INFO                       = 54032
)
